[project]
name = "example-agent"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13.9"
dependencies = [
    "adk>=0.0.5",
    "google-adk>=1.20.0",
]
